### ISSUE TITLE
Doesnt launch when i try to open it

### ISSUE THREAD

**Issue by MAXIMUSSCORP** [disepi/ambrosial#10]
even with administrator privileges, whenever I open the launcher nothing happens

in task manager "Ambrosial launcher" shows up for a few seconds on processes but nothing happens and it disappears

**Comment by OverallBell5367** [comment]
same here

**Comment by ErikPDev** [comment]
Make sure you are using the latest release 
https://github.com/disepi/ambrosial/releases/tag/1.3

**Comment by OverallBell5367** [comment]
Yes, the new release fixes everything

**Comment by ErikPDev** [comment]
> Yes, the new release fixes everything

I cannot tell if you are being sarcastic or serious.

**Comment by OverallBell5367** [comment]
Hahaha ok I can be dumb sometimes, I was serious.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by ErikPDev** [comment]
> Hahaha ok I can be dumb sometimes, I was serious. Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
> […](#)

😂 😂, you aren’t dumb. I’m very bad at understanding humor in text

**Comment by OverallBell5367** [comment]
i meant that it fixes everything with the launcher
