### ISSUE TITLE
Scrolling with mouse wheel no longer works after update to 1.19.40

### ISSUE THREAD

**Issue by Maj-ew** [disepi/ambrosial#101]
Nothing more than the title

**Comment by MSI-vortex** [comment]
Try setting the click gui style to modern.

**Comment by brunoman4006** [comment]
it actually works, or at least it's working on 1.19.50 and the new 1.19.51

**Comment by MSI-vortex** [comment]
@brunoman4006 Yes, as of zephyr 1.19.5002.0 scrolling now works.

**Comment by Humii5592** [comment]
yay
