### ISSUE TITLE
Ambrosial does not download required files in folders

### ISSUE THREAD

**Issue by ScpzzzThJ** [disepi/ambrosial#103]
On launch, Ambrosial does not download required files to their respective folders (such as banner images), leading to errors such as this one 

![image_2022-11-05_141841218](https://user-images.githubusercontent.com/82206202/200121870-e50cb571-855d-4aec-b93a-dc660a25335d.png)

**Comment by ScpzzzThJ** [comment]
I have already made sure that the problem is not caused by one of the reasons listed. I have .NET framework 4.8 installed and Yu Gothic UI Light font is also installed. My internet connection also seems to be working fine.

**Comment by adgods1** [comment]
delete the ambrosial folder

**Comment by adgods1** [comment]
AppData\Local\Ambrosial

**Comment by jonahd123** [comment]
close issue
