### ISSUE TITLE
it crashed?

### ISSUE THREAD

**Issue by wowthisisarandomuser** [disepi/ambrosial#137]
minecraft just crashed when i tried using Zephyr classic

**Comment by Humii5592** [comment]
you need to downgrade to the version of the zephyr classic that you're using. you can downgrade with [Bedrock Launcher](bedrocklauncher.github.io)

**Comment by wowthisisarandomuser** [comment]
oh

**Comment by Humii5592** [comment]
lol

**Comment by HumaanK** [comment]
you can close this issue now
