### ISSUE TITLE
Suggestion:killsults for another server(another than hive)

### ISSUE THREAD

**Issue by Rayhangege** [disepi/ambrosial#139]
I want to use killsults on Cubecraft and i cant because its only for Hive, Can you all add new server option for killsults?

**Comment by Humii5592** [comment]
@disepi tbh you could add new server options for all servers (mineplex, galaxite, pixel paradise) but thats up to you. all i really want is the cubecraft killsults.

**Comment by HumaanK** [comment]
ooh yes more killsults
