### ISSUE TITLE
Regen doesnt bypass anymore even with Disabler

### ISSUE THREAD

**Issue by ambrosialhax** [disepi/ambrosial#140]
regen now doesnt bypass, everytime i use it i just get banned , please fix this

**Comment by Humii5592** [comment]
ur the guy in the darknbthax video

**Comment by Humii5592** [comment]
what disabler mode are you using? if ur using flareonmisc disabler try cancel because ive seen people bypass with that disabler

**Comment by ambrosialhax** [comment]
not working with cancel, still bans me after it digs blocks under me

**Comment by HumaanK** [comment]
yeah recently zephyr regen has been patched

 tough luck :/
