### ISSUE TITLE
Down Scaffold

### ISSUE THREAD

**Issue by HumaanK** [disepi/ambrosial#145]
can you add on option in scaffold so that whenever you sneak with scaffold on the bridge goes down and also still saves you from falling please? thanks!

zephyr on top

**Comment by srxfiqq** [comment]
That literally already exists

**Comment by Humii5592** [comment]
oh. which mode

**Comment by HumaanK** [comment]
whoops posted on my main. as i was saying, which mode?

**Comment by HumaanK** [comment]
wait r u the yt guy

**Comment by srxfiqq** [comment]
there isnt a mode, you just hold shift and go down

**Comment by HumaanK** [comment]
...oh.

**Comment by HumaanK** [comment]
well for me the bridge goes down like 1 block and doesn't bring me down with it either
