### ISSUE TITLE
I need a answer soon

### ISSUE THREAD

**Issue by GaIaxy** [disepi/ambrosial#146]
No issue i think...

but how do i load-in/import a config that i have downloaded from mediafire into zephyr?

**Comment by GaIaxy** [comment]
anyone know?

**Comment by GaIaxy** [comment]
i went to C:\Users\[Galaxy]\AppData\Local\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\RoamingState\project-halcyon\configurations

but i didn't find it

**Comment by ambrosialhax** [comment]
you go to that directory you said, after that go to the game, type  .config in chat and you should see it

**Comment by HumaanK** [comment]
save the config to that directory then in game do .config load (the config name)
