### ISSUE TITLE
Module renamer and module type renamer

### ISSUE THREAD

**Issue by HumaanK** [disepi/ambrosial#150]
@disepi can you add a command to rename modules to other names
the command goes like this:

`.modulerename Aura Killaura` (changing module name to "Killaura" instead of "Aura")

`.modulerename Fly Flight` (changing module name to "Flight" instead of "Fly")

`.modulerename Speed Bhop` (changing module name to "Bhop" instead of "Speed")

can you also make it so that you can change the name of the type of the module
the command goes like this:

`.moduletyperename Fly Flareon Hive` (changing mode name to "Hive" instead of "Flareon")

`.moduletyperename Aura Switch Multi` (changing mode name to "Multi" instead of "Switch")

`.moduletyperename Speed FlareonStrafe Flareon` (changing mode name to "Flareon" instead of "FlareonStrafe")

**Comment by disepi** [comment]
Already exists as `locale` command

**Comment by HumaanK** [comment]
uh ok

**Comment by HumaanK** [comment]
so how does one use the `.locale` command?
