### ISSUE TITLE
Minecraft not open?

### ISSUE THREAD

**Issue by FrancisDeppe** [disepi/ambrosial#153]
Whenever I try launching it, its says "open Minecraft first!"

**Comment by HumaanK** [comment]
so open minecraft duh

**Comment by HumaanK** [comment]
thats how its supposed to run
it injects the client into the game so it needs to be opened first

**Comment by FrancisDeppe** [comment]
Except I do have minecraft open?

**Comment by HumaanK** [comment]
idk then
