### ISSUE TITLE
cubecraft disabler stopped working

### ISSUE THREAD

**Issue by byp4ss3r** [disepi/ambrosial#158]
looks like cubecraft devs finally decided to do something about their god awful anticheat,

the disabler no longer does anything. I tested a bunch of things and it seems like they've written some new code specifically made for blocking zephyr.

horion still works (and all their hacks), which is funny as hell.

let's see if a fix can be made?

**Comment by sigmauser50** [comment]
ngl this was a good change, me myself (a cheater) feels that if a server's anticheat can be fully disabled, its no fun, glad they do something to patch zephyr (but not horion lol)

**Comment by HumaanK** [comment]
bro ive been making so many cubecraft configs and i never got to use them and now the disabler is patched??

@disepi FIX THIS PLEAAAAAAAAAAAAAAAASEEEEEEE

**Comment by HumaanK** [comment]
horion disabler doesnt even work i just get kicked because

"Your movement was out of sync"

**Comment by Humii5592** [comment]
try celsius client it has full sentinel disabler

**Comment by Humii5592** [comment]
yeah however disepi made a video on cc full disabler so it'll probably be added in the next version of zephyr
