### ISSUE TITLE
update to 1.19.60

### ISSUE THREAD

**Issue by sigmauser50** [disepi/ambrosial#161]
pleas update it asap with some fix including killaura strafe not working, readd flareon mode in speed, add regen type only mine visible blocks, hive disabler

**Comment by HumaanK** [comment]
YES FLAREON MODE NEED TO BE READDED AND KILLAURA STRAFE MUST BE FIX YES YES YES
WEKUFYGEQTJRYGFEUKQYRFGQHERGFKYEHQFKQYEGFRUYGE

sorry im going a bit insane

**Comment by sigmauser50** [comment]
> List of things that should be added:
> 
> Update to 1.19.60 (obviously) Flareon mode of speed (#113) FlareonGround mode of speed (#149) Aura strafe Fix cubecraft disabler (#158) .effect command (#138) Killsults for other servers (#139) Module renamer and module type renamer (#150) NoScreenBob module (#147)

and regen
