### ISSUE TITLE
Ataraxia has an unremovable virus

### ISSUE THREAD

**Issue by TheDeveloperDD1** [disepi/ambrosial#18]
I installed Ataraxia to my computer since I've tried Zephyr but as it finished installation it say "Virus Detected" I deleted the other 2 viruses but the virus named "Trojan:Win32/Wacatac.B!ml" can't be deleted nor quarantined. I tried to permanently delete the files and the Ambrosial app but it still stay. How do I remove this? Is this very harmful?

**Comment by disepi** [comment]
literally drop ataraxia into dnspy and you can see its source, i'm not bothering to type anymore just figure it out urself
