### ISSUE TITLE
Sentinel Disabler has been completely blocked

### ISSUE THREAD

**Issue by HumaanK** [disepi/ambrosial#185]
Even when I'm not moving but I have speed on, I get banned.

i hate seeing the "[SENTINEL] zephyr user has been banned for cheating" chat message flash before my very eyes before I get banned.

Please bring the full disabler back.

I've been making many configs for Cubecraft but I never got to try them.

**Comment by byp4ss3r** [comment]
Oh it's not disepi,

CubeCraft just finally got around to noticing the disabler. If you still want to to bypass it, use Horion, or just TURN OFF THE DISABLER.

They didn't superbuff their anticheat. Just made it immedietly flag zephyr code.

Their anticheat is ass, remember. I made a config with Scaffold, Aura, Friction Speed, and it works like a charm. Haven't gotten banned except when I snipe streamers

**Comment by Humii5592** [comment]
ok ill try
but horion disabler gets me kicked because

"Your movement was out of sync"

**Comment by Humii5592** [comment]
but isnt turning off the disabler going to get me banned for sure?

**Comment by Humii5592** [comment]
i got kicked you idiot

**Comment by Nya-Enzo** [comment]
Because your config is ass probably

**Comment by byp4ss3r** [comment]
> i got banned you idiot

https://www.youtube.com/watch?v=Q5IYbJ2ObDo
Shameless promotion of Byp4ss3r config :)

Works!

**Comment by Nya-Enzo** [comment]
yeah isn't that hard to make a config, sentinel is ass
