### ISSUE TITLE
`DesyncBoost`

### ISSUE THREAD

**Issue by Humii5592** [disepi/ambrosial#193]
Please add the `DesyncBoost` mode of Speed and don't only give it to aeolus users it's mean >:(

**Comment by disepi** [comment]
it's in aeolus only for a reason

**Comment by Humii5592** [comment]
why is it only in aeolus then

**Comment by Humii5592** [comment]
and there is no way its a ¨beta¨ feature because desyncboost has been in aeolus for like billions of versions but never added to zephyr public

**Comment by Nya-Enzo** [comment]
Imagine if aeolus was free, way more people would be using it right ? Then it would get patched more easily, and also i guess that since some bypasses are not a easy to do as others you will put them on the paid version instead of the free version

**Comment by Humii5592** [comment]
oh that makes sense
