### ISSUE TITLE
Every time I run Ambrosial I get an error.

### ISSUE THREAD

**Issue by MaruFagger** [disepi/ambrosial#195]
I also tried installing .NET framework 4.7.1, but it gives an error. I also installed the font, but the error pops up. help!
![image](https://user-images.githubusercontent.com/75873629/221328445-72801d5b-8948-4576-b543-06159b39e95d.png)

**Comment by Humii5592** [comment]
just click ok and ignore it

**Comment by disepi** [comment]
Delete all the items in your `%localappdata%\Ambrosial` folder, you probably tried to import a client with invalid information
