### ISSUE TITLE
Comandos de .dupe .enchant .give desaparecieron?

### ISSUE THREAD

**Issue by iram123456** [disepi/ambrosial#196]
Hola queria preguntar porque los comandos  .dupe .enchant .give desaparecieron? no me aparesen en .help y no me deja ejecutarlos

**Comment by Humii5592** [comment]
creo que eso me paso a mi tambien

**Comment by iram123456** [comment]
amigo no sabes como solucionarlo  ati si te deja ejecutar esos comandos¡?

**Comment by iram123456** [comment]
esque nose como solucionarlo
