### ISSUE TITLE
No MC Detected?

### ISSUE THREAD

**Issue by music-discussion** [disepi/ambrosial#20]
I'm using Ambrosial, and I'm on 1.17.10 with the latest Zephyr and it wont inject because it says it cant get to Minecraft when its open

**Comment by ErikPDev** [comment]
Try reinstalling minecraft from Windows Store. MCLauncher shouldn't be used.
Or click the gears button on ambrosial
![image](https://user-images.githubusercontent.com/33035080/132286853-bb8ab539-cdca-4dde-abe2-81ff93bb1b08.png)
And disable Should Check Verison
![image](https://user-images.githubusercontent.com/33035080/132286901-55bc3ca4-6f33-4424-9bce-34fdce7248a1.png)
