### ISSUE TITLE
Sentinel Disabler got completely patched

### ISSUE THREAD

**Issue by Humii5592** [disepi/ambrosial#200]
bro pls fix sentinel disabler i turn on sentinel disabler no other hacks then i get banned pls fix

**Comment by iram123456** [comment]
humi sati te aparecen los comandos de .dupe y .enchant

**Comment by Humii5592** [comment]
`.dupe` y `.enchant` han sido parcheados desde el 1.19.60. Esto es lo mismo con `.give` y `.cbe` y `.nuke`.
