### ISSUE TITLE
ItemAnimations `Slide` mode does not work

### ISSUE THREAD

**Issue by Humii5592** [disepi/ambrosial#203]
I tried the small items module aswell but it didn't work. It just stays as 1.7 mode

**Comment by iram123456** [comment]
humii sabes si aun sigen los comandos de .enchant y .dupe

**Comment by Humii5592** [comment]
No estoy seguro, no he probado los comandos todavía.

**Comment by iram123456** [comment]
gracias como quiera si puedes luego que pases por ay me dises si encuentras una solucion esque esos eran los comandos que mas me gustaban

**Comment by Humii5592** [comment]
Si todavía no ha agregado los comandos de nuevo actualización, intente abrir un montón de problemas o publique comentarios en su (canal de YouTube)[youtube.com/@gaberbruh]

**Comment by Humii5592** [comment]
youtube.com/@GaberBruh

Este es el canal de YouTube de Disepi

**Comment by iram123456** [comment]
A garacias bro deja checo en su canal si sabes algo de los comandos me abisas porfa bro

**Comment by Humii5592** [comment]
Bueno, ningún problema

**Comment by Humii5592** [comment]
De hecho, comprobaré si los comandos existen ahora.

**Comment by iram123456** [comment]
gracias bro

**Comment by Humii5592** [comment]
Los comandos siguen sin funcionar :(

**Comment by iram123456** [comment]
Esta bien alomejor los meten en la nueva actualizacion del juego

**Comment by Humii5592** [comment]
La manipulación del inventario se parchó, por lo que comandos como `.cbe`, `.give` y `.enchant` ya no funcionan después de la última actualización :(
