### ISSUE TITLE
can i have aeolus lmao

### ISSUE THREAD

**Issue by Humii5592** [disepi/ambrosial#205]
can i have aeolus i wont leak i promise pleasejhsqgeufhsqpiejfujw[eijfhqp3hpofgriqthgqerkiiqejhwrguhqjwoefhewriq

**Comment by Humii5592** [comment]
you can trust me

**Comment by Nya-Enzo** [comment]
Wait till restock and purchase it, it's not that expensive and it's worth it anyways

**Comment by Humii5592** [comment]
ok how much is it

**Comment by Humii5592** [comment]
hasn't restocked in ages plus i wanna buy lifetime and i got no money on me
