### ISSUE TITLE
`.give`, `.enchant` and `.cbe` commands have been removed

### ISSUE THREAD

**Issue by Humii5592** [disepi/ambrosial#206]
@disepi Please add the `.give`, `.enchant` and `.cbe` commands back

**Comment by iram123456** [comment]
gracias bro

**Comment by Humii5592** [comment]
Ningún problema

**Comment by jonahd123** [comment]
yea

**Comment by jonahd123** [comment]
pls do i miss them :(

**Comment by LevenLMR** [comment]
Those commands stopped working with minecrafts latest update. That's why they got removed. I'm sure there working to fix them and bring them back once they do so because they some of the most important commands to have.

**Comment by jonahd123** [comment]
> Those commands stopped working with minecrafts latest update. That's why they got removed. I'm sure there working to fix them and bring them back once they do so because they some of the most important commands to have.

THANK goodness I thaugt you were becomeing the horrid onix client

**Comment by iram123456** [comment]
@LevenLMR  gracias bro estoy seguro de que van a volver a funcionar

**Comment by Humii5592** [comment]
:(

**Comment by Humii5592** [comment]
goddamnit patched inv manipulation
