### ISSUE TITLE
pls update

### ISSUE THREAD

**Issue by danglezsdadad** [disepi/ambrosial#210]
ive been having a problem with zephyr because for new people who downloaded the version of zephyr after the 1.19.63 update cant launch/inject. so please update this issue that would be very nice

**Comment by danglezsdadad** [comment]
![Screenshot 2023-03-05 081508](https://user-images.githubusercontent.com/127055466/222986172-767181a7-02c2-4046-8636-8fd9995e9b5b.png)

**Comment by disepi** [comment]
Disable the version check feature within Ambrosial's settings page, this should allow you to inject

**Comment by danglezsdadad** [comment]
> 

Still doesnt work, I even tried installing c++.

**Comment by danglezsdadad** [comment]
Could you possibly make a new version, after the update with 1.19.63 zephyr hasnt been working.
