### ISSUE TITLE
Algien sabe si alguna opcion del Ambrosial Launcher puedo meternme a un servidor aunque este Baneado

### ISSUE THREAD

**Issue by iram123456** [disepi/ambrosial#211]

**Comment by Humii5592** [comment]
Obviamente, eso no será posible con Ambrosial. Simplemente haga un alt o cambie su IP si tiene una IP prohibida.

**Comment by iram123456** [comment]
gracias bro esque me banearon de un servidor y queria ver si avia otra manera de entrar k no supiera pero ya intente cambiarme de ip pero sige apareciendome lo mismo como quiera garacias bro

**Comment by Humii5592** [comment]
@iram123456 En Zephyr Client, hay una forma de eludir las prohibiciones de IP. Simplemente cree una nueva cuenta, active el módulo "DeviceIDSpoof" en Zephyr y debería poder unirse.

**Comment by iram123456** [comment]
gracias amigo
