### ISSUE TITLE
Command request

### ISSUE THREAD

**Issue by theusernamePhantom676isnotavailable** [disepi/ambrosial#217]
I tought you have commands like .give or .enchant but you dont have it, could you please add it? they could be helpful

**Comment by Humii5592** [comment]
inv manipulation is patched, don't know how many times i gotta say it

**Comment by Humii5592** [comment]
other clients are all suffering with this issue

**Comment by Humii5592** [comment]
its most likely going to be patched forever, give up already

**Comment by iram123456** [comment]
no ay alguna manera de eliminar ese parche
porque los comandos funcionan pero en los mundos no en los servidores
