### ISSUE TITLE
update 1.19.70

### ISSUE THREAD

**Issue by Humii5592** [disepi/ambrosial#219]
hi can you update zephyr to 1.19.70? thx!

**Comment by iram123456** [comment]
aun no sacan la actualisacion vdd

**Comment by Humii5592** [comment]
¿Qué es la "actualización de vdd"?

**Comment by iram123456** [comment]
Que aun no actualizan el launcher Ala version 1.70?

**Comment by Humii5592** [comment]
Sí, sorprendentemente, todavía no se han actualizado a 1.19.70. Sin embargo, la degradación solucionará esto. Si cambia a 1.19.60, puede continuar usando Zephyr Client.

**Comment by iram123456** [comment]
gracias
