### ISSUE TITLE
ITS NOT WORKING

### ISSUE THREAD

**Issue by Adapos** [disepi/ambrosial#226]
Minecraft is crahing shortly after I injected

**Comment by saph444** [comment]
im having the same problem!

**Comment by likegithubmomo** [comment]
same

**Comment by dreadthief125** [comment]
its getting patched meanwhile use PolarZ or Horiron

**Comment by dreadthief125** [comment]
or use https://bedrocklauncher.github.io/ and launch a working version and inject working zephyr
