### ISSUE TITLE
For some reason my inspect close key doesnt work with the clickgui

### ISSUE THREAD

**Issue by NoobPJJason** [disepi/ambrosial#23]
so whats happening is yesterday i was playing with the gui in game everything did well
but then later in the day when i started up minecraft with the gui and clicked Inspect it did nothing and i couldnt close the gui anymore how to fix this or what am i doing wrong?

**Comment by disepi** [comment]
This Github repo is for the Ambrosial launcher, not whichever client you're using. Suggest/report whatever you want in the client's discord
