### ISSUE TITLE
Latest Version Crashes Minecraft

### ISSUE THREAD

**Issue by LevenLMR** [disepi/ambrosial#230]
I understand your probably working on this. Just making sure it's the top of the issues list. Thank you.

**Comment by LevenLMR** [comment]
> whens 1.19.73 comin out

Believe it came out on the 29th of march for official bedrock. It was bug fixes mostly. I would assume we will see an update to match with ambrosial and zephyr pretty soon.

**Comment by MOISTPRETZELZ** [comment]
game crashes on startup with ambrosial
