### ISSUE TITLE
Blank screen when opening the .exe

### ISSUE THREAD

**Issue by beenycool** [disepi/ambrosial#238]
Hello! Whenever I open the .exe I get a blank screen. This is shown in the video down below. Thank you for your time.

https://user-images.githubusercontent.com/129210955/236550682-119a75d6-0b5e-4366-8a43-f5bc4f50fd4c.mp4

**Comment by Humii5592** [comment]
wtf LMAO

**Comment by beenycool** [comment]
nvm fixed it you just need to download a vpn
