### ISSUE TITLE
all hack clients are missing in ambrosial how do i fix this

### ISSUE THREAD

**Issue by XplodinNdr08** [disepi/ambrosial#25]
when i added horion client to ambrosial all hack clients disappeared how do i fix this?

**Comment by XplodinNdr08** [comment]
![Screenshot (29)](https://user-images.githubusercontent.com/66173981/128870745-5c3a01b1-2372-4f06-ac26-657adc104df3.png)

**Comment by XplodinNdr08** [comment]
![image (1)](https://user-images.githubusercontent.com/66173981/128871271-5456257d-fde7-4bb6-9780-21d656b46a8d.png)

**Comment by XplodinNdr08** [comment]
if you cant please add the ability to redownload all hack clients back into it incase we lose them for what ever reason

**Comment by XplodinNdr08** [comment]
for goodness sakes the burrito hub discord couldnt help me and the zephyr discord couldnt help me nothing was able to help me please help m fix this?

**Comment by disepi** [comment]
Delete %localappdata%\Ambrosial\assets\userimport\importedclients\ if nothing shows up in launcher after adding new client

**Comment by XplodinNdr08** [comment]
didnt work but when i restarted my pc it was fixed thanks anyway
