### ISSUE TITLE
Virus detected

### ISSUE THREAD

**Issue by crpalo** [disepi/ambrosial#27]
MacAfee deemed my download unsafe so I decided to put the file through virus total.
Here's the URL to my scan https://www.virustotal.com/gui/file/af2d86a0ceee44582df0e96ff27bb07fac48248a352aae8d9af296486ae0219a/detection 
Also attached is a screenshot.
![proof of trojan](https://user-images.githubusercontent.com/90151820/132136530-f10a277a-c4ec-481f-9953-7b5f02499210.PNG)

**Comment by disepi** [comment]
Please use your common sense
