### ISSUE TITLE
More Nuget Packages needed

### ISSUE THREAD

**Issue by tubaplayerdis** [disepi/ambrosial#28]
when looking at the readme.md file, I saw that you only needed to add fody to build yourself. But you also need these,

**DiscordRichPresence**
**Costura.Fody specifically version 5.3.0**
**Newtonsoft.json**
**Guna.UI2.WinForms**

just to help people who want to modify

**Comment by FloppyDolphin57** [comment]
they arent included in source because they take up a lot of space

**Comment by tubaplayerdis** [comment]
I understand that just it would be better if they told you that you needed to install them in the readme

**Comment by FloppyDolphin57** [comment]
> 

if someone cant install a few packages i dont really think they should be touching source code

**Comment by tubaplayerdis** [comment]
I think, but as my 8th science teacher said, what if random wanted to read, use, interpret and understand what you made, what do you need to do?. Just my idea

**Comment by disepi** [comment]
I have added these packages into the readme. Might fix later by including the package DLLs in the source
