### ISSUE TITLE
Launcher

### ISSUE THREAD

**Issue by rileusawed** [disepi/ambrosial#3]
Why isent the client opening. It opened when i first got it

**Comment by ErikPDev** [comment]
The server is down. Check #2 on more information.

**Comment by rileusawed** [comment]
have you fixed it?

**Comment by lilghoul7554** [comment]
A few weeks ago I downloaded it to use it in minecraft bedrock, it worked fine but yesterday I detected that it contained a virus, I deleted it and downloaded again
"ambrosial", but it gave me a virus message again, (I downloaded it from github on the original download page) the virus is "Contebrew.A! ml"

help.

**Comment by rileusawed** [comment]
It’s a false virus it is not one it’s marked as on thought
