### ISSUE TITLE
I can't inject project halcyon of 1.17.41.1 (injected but no response)  But trero external can

### ISSUE THREAD

**Issue by kamq32** [disepi/ambrosial#36]
I can't inject project halcyon of 1.17.41.1 (injected but no response)

But trero external can

**Comment by kamq32** [comment]
11/28/2021 12:47:51.344 || [AMBROSIAL-LAUNCHER] : Client Project Halcyon seems to be an DLL type file, downloading...
11/28/2021 12:47:51.353 || [AMBROSIAL-LAUNCHER] : Project Halcyon seems to be cached! Canceled download.
11/28/2021 12:47:51.411 || [AMBROSIAL-LAUNCHER] : Project Halcyon (project-halcyon.dll) has been injected at 2021/11/28 12:47:51

**Comment by kamq32** [comment]
I can't understand

**Comment by disepi** [comment]
Download VC redist at https://aka.ms/vs/17/release/vc_redist.x64.exe
