### ISSUE TITLE
Open GUI Hotkey Not Working

### ISSUE THREAD

**Issue by DermicUnicorn32** [disepi/ambrosial#37]
When I have Project Halcyon injected and I press Insert, nothing happens.

**Comment by byCRXHIT** [comment]
Go into a single Player World,
type ".bing ClickGUI m" and then
press M to open the menu

**Comment by disepi** [comment]
Toggle NUM lock and press `Insert` or hold `FN` while pressing `Insert` or do `.bind ClickGUI L` ingame to relocate the UI key to L if the previous methods don't work.
