### ISSUE TITLE
Ambrosial Is messed up :/

### ISSUE THREAD

**Issue by davidplayz123** [disepi/ambrosial#4]
So i decided to install ambrosial to get REVENGE on my friends because they ended up killing me and taking my stuff so you knowyou gotta hack to kill them. but when i open the app it loads the app but i cant click on anything idk what to do how do ii fix this?
![image](https://user-images.githubusercontent.com/68371492/122651621-8d55b200-d129-11eb-9f5b-c83679c72de2.png)

**Comment by disepi** [comment]
Try reinstall Minecraft, this only happens if your MCBE couldn't be found in the WindowsApps path. Also try disable your antivirus.
