### ISSUE TITLE
virus in ambrosial (Contebrew.A! ml)

### ISSUE THREAD

**Issue by lilghoul7554** [disepi/ambrosial#5]
A few weeks ago I downloaded it to use it in minecraft bedrock, it worked fine but yesterday I detected that it contained a virus, I deleted it and downloaded again
"ambrosial", but it gave me a virus message again, (I downloaded it from github on the original download page) the virus is "Contebrew.A! ml"

the virus was detected by McAfee :/

help.

**Comment by ErikPDev** [comment]
This is interesting

**Comment by ErikPDev** [comment]
Contebrew.A! ml is an adware virus.

**Comment by ErikPDev** [comment]
But what's odd that VirusTotal doesn't detect it as a virus
https://www.virustotal.com/gui/url/0ac7212c9862eeccc1f2664c4a379f6d2695f441ad5882653a0d3e676c900a28/detection

**Comment by ErikPDev** [comment]
False virus?

**Comment by Wendys-corp** [comment]
> A few weeks ago I downloaded it to use it in minecraft bedrock, it worked fine but yesterday I detected that it contained a virus, I deleted it and downloaded again
> "ambrosial", but it gave me a virus message again, (I downloaded it from github on the original download page) the virus is "Contebrew.A! ml"
> 
> the virus was detected by McAfee :/
> 
> help.

your using the worst anti virus ever lol

**Comment by megahendick** [comment]
Ok well 1 get rid of mc afee and get a real av like malware bytes and ambrosial is literally open source if there really was a virus there would be a ton of proof its a false positive

**Comment by disepi** [comment]
The source for Ambrosial is right there for you to check for any "viruses". Not sure why you would open an issue when you answer to your question to it being a virus is literally 2 clicks away.

And to fix your issue, just disable your antivirus or try building Ambrosial yourself.

**Comment by ErikPDev** [comment]
FYI: Some users rebuild Ambrosial with a virus to gain unauthorized access to computers. Make sure to only download Ambrosial from this GitHub page release tab

**Comment by wavalava** [comment]
its not a virus its a false positive idiot
