### ISSUE TITLE
When injected, the game crashes

### ISSUE THREAD

**Issue by LordBombardir** [disepi/ambrosial#56]
When injecting any mod, the game crashes. What to do?
Everything is fine in the log.
> 03.03.2022 12:02:36.779 || [AMBROSIAL-LAUNCHER] : Zephyr downloaded. Cached.
> 03.03.2022 12:02:36.825 || [AMBROSIAL-LAUNCHER] : Zephyr (project-halcyon.dll) has been injected at 03.03.2022 12:02:36

Minecraft version - 1.18.1201.0

**Comment by surveybuilder-admin** [comment]
outdated

**Comment by disepi** [comment]
Please use a client which has the version matched to your installed game
