### ISSUE TITLE
when i launched zephyr first time then it worked but then it crashed one time then i cloased mc n ambrosial then reopened both n then when launched it didnt then i reopened again n it zephyr launched bt when i got into game n press insert i can see only auditory i couldnt see any other hacks. help me

### ISSUE THREAD

**Issue by 111-pixel** [disepi/ambrosial#57]

**Comment by 111-pixel** [comment]
n i deleted ambrosial n redownload now it wont even launch

**Comment by 111-pixel** [comment]
![image](https://user-images.githubusercontent.com/101633133/158351367-44e5421b-3777-40ec-8342-750def61134b.png)

**Comment by 111-pixel** [comment]
see its only audiotry showing n it launched

**Comment by 111-pixel** [comment]
@disepi help?]

**Comment by Ruzzki** [comment]
What is ur resolution of the game

**Comment by 111-pixel** [comment]
what do u mean what resolution hw to check?

**Comment by Ruzzki** [comment]
Actually, everything is stacked in 1 place, just drag them apart.
