### ISSUE TITLE
ERROR could not find cached clients.json

### ISSUE THREAD

**Issue by acowsays** [disepi/ambrosial#6]
got this error. not sure what to do...
need a URL it would seem
![explorer_hkkKcaXujn](https://user-images.githubusercontent.com/47616873/122850151-c2edcd00-d2da-11eb-98bf-b228ef385976.png)
![explorer_3uD6d3gwor](https://user-images.githubusercontent.com/47616873/122850162-c8e3ae00-d2da-11eb-8d57-90d66479b20c.png)
![explorer_ypCfDSl6vW](https://user-images.githubusercontent.com/47616873/122850180-cd0fcb80-d2da-11eb-8da4-07ffd42acfb8.png)
![explorer_WGDWtj0Zht](https://user-images.githubusercontent.com/47616873/122850192-ced98f00-d2da-11eb-8467-05124959bb1d.png)

**Comment by a006yt** [comment]
I am facing the same issue

**Comment by quinnzaballa** [comment]
[Ambrosial.zip](https://github.com/disepi/ambrosial/files/6694154/Ambrosial.zip)
This file dont have malware or shit on it. this works fine. if it shows this error msgbox

![Untitled](https://user-images.githubusercontent.com/58278258/122924106-fc384280-d397-11eb-9bba-42e74fa96ca9.png)


Press "Yes" and voila. that should work. - Force#6581

Join ambrosial discord server and ask problems.

**Comment by disepi** [comment]
Fixed in latest release
