### ISSUE TITLE
i downloaded ambrosial again after deleting my ambrosial nn now when i launch zephyr n press insert button its only showin auditory it aint showing other hacks like combat movement world  visual n others ill attach a pic of it here 

### ISSUE THREAD

**Issue by LilMochiMin1980** [disepi/ambrosial#60]
![image](https://user-images.githubusercontent.com/102237352/159720098-f2b65cd7-b87b-4130-9d51-1576d64ccd70.png)

**Comment by Ruzzki** [comment]
Everything is staked in 1 place, just move the auditory and a new one will appear.
