### ISSUE TITLE
Adding support for ARM64 devices

### ISSUE THREAD

**Issue by SunshroomChan** [disepi/ambrosial#61]
So when you tried to inject it but your computer running ARM64 so it won't happen when i pressed inject it on Windows 11 ARM64 version
I have installed on vc_redistx64 still normal and due to it was ARM based processor it won't work 
Please add support for that
Thanks!

**Comment by MkdSmd** [comment]
I think it didn't work on Windows 11
I can inject it in windows 10 but when I upgrade to windows 11 when I press launch it won't happen
My computer is x64-based processor

**Comment by SunshroomChan** [comment]
> 

and i have another pc x64 processor windows 10 so i can use that normally

**Comment by SunshroomChan** [comment]
> I think it didn't work on Windows 11 I can inject it on windows 10 but when I upgrade to windows 11 when I press Launch it won't happen My computer is x64-based processor

Nah it work find for ARM64 architecture because windows 11 have support x64 emulation so you can install vc_redistx64 and inject normally
