### ISSUE TITLE
Hitbox Bug (Zypher)

### ISSUE THREAD

**Issue by dialza** [disepi/ambrosial#65]
I’m surprised this hasn’t been mentioned but everytime hitbox is toggled, between 5-30 seconds after toggled Minecraft freezes then crashes. The time varies differently all the time but within a minute after toggled, the whole game closes. When you get a chance, please look into this, it’s the only bug ive noticed so far since using Zephyr.

**Comment by aternos24** [comment]
make sure to turn off hitbox check in antibot

**Comment by disepi** [comment]
This should be fixed on the latest version - the entity collection function was the main cause of this and it has been refactored since then. If any problem occurs, feel free to open a new issue.

**Comment by aternos24** [comment]
It's fixed some thanks
