### ISSUE TITLE
New storage ESP

### ISSUE THREAD

**Issue by ZaferKilic** [disepi/ambrosial#68]
Hey Developers! I will give you a suggestion! In the 2B2T server, people put the items they store in droppers or launchers, and it becomes impossible to find them. So can you add a release and a launcher ESP?

**Comment by Maxthegamerthefirst** [comment]
? Who is this I think this is the wrong email

**Comment by jawdropper16** [comment]
launchers?

**Comment by ZaferKilic** [comment]
Oh sorry for my english:)

I Players hide their valuables inside Droppers and Traps in the Game. And most of them can't show cheats. Can you add this?
