### ISSUE TITLE
Zephyr doesn't work

### ISSUE THREAD

**Issue by SwoOsh-Savage12** [disepi/ambrosial#7]
Whenever I try injecting it just crashes Minecraft this is happening with all my friends too.

**Comment by ErikPDev** [comment]
Zephyr isn’t updated to the latest Minecraft Version, just wait a while for the update.

**Comment by pikachub2005** [comment]
> Zephyr isn’t updated to the latest Minecraft Version, just wait a while for the update.

1.17.0? It crashes for me as well.

**Comment by disepi** [comment]
This is not an issue with Ambrosial. Instead, report this error in the Discord guild for Zephyr
