### ISSUE TITLE
Too big X-Ray

### ISSUE THREAD

**Issue by LordBombardir** [disepi/ambrosial#75]
X-Ray shows too many blocks, so the generation of PocketMine-MP cores of API version 4.x throws the player out of the game.
![image](https://user-images.githubusercontent.com/60620262/170491380-0e3d8390-c275-4ada-bb56-93669c15197b.png)

**Comment by LordBombardir** [comment]
* in horion

**Comment by disepi** [comment]
This occurs because of how Zephyr handles reloading of chunks which uses a workaround related to breaking/interacting with blocks. If I have time, I'll refactor this to change how this works. Thank your for the bug report + sorry for the wait.
