### ISSUE TITLE
Horion doesn't work on ambrosial 

### ISSUE THREAD

**Issue by surveybuilder-admin** [disepi/ambrosial#77]
Whenever I try activating Horion on ambrosial, I get an _Unhandled expectation_ do you know how you can fix that?

**Comment by SoFranci** [comment]
Download horyon on theyr site :)

**Comment by surveybuilder-admin** [comment]
Can't the site isn't secured, and my PC just doesn't like, it, but thanks for the reply

**Comment by SoFranci** [comment]
the site is secure https://horion.download/
is https

**Comment by surveybuilder-admin** [comment]
it works now, it wasn't earlier
