### ISSUE TITLE
Amborisal wont open

### ISSUE THREAD

**Issue by UwUmenxd** [disepi/ambrosial#83]
when im opening ambroisal this is showing i have everything installed. Yesterday it worked

![image](https://user-images.githubusercontent.com/106464411/180595180-956e3e21-06f3-4a7e-9c89-7e3cd2ecc9a3.png)

**Comment by Motivated669** [comment]
hey it might help with your problem, did you download visual studios community 2019 it might be the cas because ambrosial cannot inject zephyr without it

**Comment by gmankab** [comment]
same provlem

tried but not helped:
- Installing Visual C++ Redistributable
- installing .NET Framework Redistributable

really helped:
removing backround image from app

download patched executable - [github.com/gmankab/ambrosial-fix/releases/download/08.26.2022_fix/Ambrosial.exe](https://github.com/gmankab/ambrosial-fix/releases/download/08.26.2022_fix/Ambrosial.exe)
diff - [github.com/gmankab/ambrosial-fix/commit/e1530a5d5af8b00b114fb32e63a02d81e42f7214](https://github.com/gmankab/ambrosial-fix/commit/e1530a5d5af8b00b114fb32e63a02d81e42f7214)

before fix:
![image](https://user-images.githubusercontent.com/73340745/186926413-14d16102-37d9-42a5-abfc-b959895f2823.png)
after fix:
![image](https://user-images.githubusercontent.com/73340745/186926578-baad1ed5-bfb7-458b-bf0d-c4abf3044fc3.png)
![image](https://user-images.githubusercontent.com/73340745/186926806-e03121ce-3a93-4fed-8bf2-0ac0dfae269d.png)
