### ISSUE TITLE
Port commands from horion to zephyr

### ISSUE THREAD

**Issue by demowmn** [disepi/ambrosial#89]
Some commands and features, (such as .setlore, .rename, and the full usage of .enchant which i have made a issue of before - #85 ) were incredibly useful for mapmaking and making actual illegals, however these features aren't currently supported in zephyr. I think it would be pretty useful to get these features back considering horion is no longer supported.

**Comment by thekoreandoctor** [comment]
yes please

**Comment by Humii5592** [comment]
yeah thats a good idea

**Comment by Humii5592** [comment]
but horion is supported now so u can use horion

**Comment by HumaanK** [comment]
still he should add it
