### ISSUE TITLE
just gave me "let this app change your device?" popup and didnt run the application

### ISSUE THREAD

**Issue by OverallBell5367** [disepi/ambrosial#9]

**Comment by ErikPDev** [comment]
That’s odd, Screenshots?

**Comment by wavalava** [comment]
run as admin > yes > should be open

**Comment by OverallBell5367** [comment]
A screenshot would not help that much, because when I get the notification, it blurs the rest of my screen. When I clicked "run as administrator" and agree to it "changing my device" Minecraft flashes red at the bottom of the screen. That, and whenever I take a screenshot, it doesnt include any open tabs, just shows my app icons.
