### ISSUE TITLE
Flying Damage

### ISSUE THREAD

**Issue by LevenLMR** [disepi/ambrosial#92]
Any time the flight mod is active it causes damage. I think it's due to the game thinking your phased into a block. Probably recognizing air blocks as solid.

**Comment by Dream23322** [comment]
no, its because you character server side goes up and down, so yo hit the ground taking fall damage

**Comment by brunoman4006** [comment]
When you enable flight, you can see yourself flying, but the server sees you like your character is making super long jumps, and constantly falling down, so the server thinks you're actually that up and it traces the fall damage until you reach a block, if it's water then the fall damage cancels and everyting ok, but if there was a solid block it hurts

**Comment by Humii5592** [comment]
just turn on nofall
