### ISSUE TITLE
Good luck

### ISSUE THREAD

**Issue by Dream23322** [disepi/ambrosial#96]
Ok, so if im gonna be honest most of the visuals in this client are ass, so here are some ideas:
- Custom clickgui's
- Tenacity Style visuals in most visual modules bc tenacity acctually looks good
- more fonts
- rounded setting on keystrokes
- add that cool ass looking arraylist thing where it looks like its above the rest of the screen (layer thing also would be cool with scoreboards that harras you on the side of the screen)
- ANTIVOID WORK ON MINEPELXXXXXXXXXXXXXXXXXXX
- killaura have the visualise thing (the ring around you and the sigma style thing around the other player)
- OMG please, a playtime thing, like that thing in packet, but the tenacity visuals work lol
- BETTER TARGET HUDS
- and better ESP's bc idk how to import custom ones or how to get them lol
- BPS graph
- speed that works on nethergames
- ANTIBOT IGNORE THE NETHERGAMES BOT ITS SOOOOOOOOOOO ANOYING (there is a way to just kill the bot lol)
- More clickgui's 
- ALLOW THE CLICKGUI TO BE SMALLER/LARGER!!!!!!!!!!!!!!!! 

sorry.

**Comment by disepi** [comment]
This repo is for Ambrosial, not any clients included inside of it

**Comment by Dream23322** [comment]
Where can i then?
